### ISSUE TITLE
Globals从application.properites文件获取参数的问题

### ISSUE THREAD

**Issue by coolarmy** [TomYule/NutzSite#10]
在真实环境中如果有同路径的application.properites文件存在的时候，Globals文件还是从jar包内获取，所以需要优化更改一下，我修改如下：
    static {
        try {
            InputStream is;
            //优先获取jar包外面的配置文件
            String path = System.getProperty("user.dir");
            File prop = new File(System.getProperty("user.dir")+File.separator+"application.properties");
            if(prop.exists()) {
                is = new FileInputStream(prop);
            } else {
                //获取当前类加载器
                ClassLoader classLoader = Globals.class.getClassLoader();
                //通过当前累加载器方法获得 文件db.properties的一个输入流
                is=classLoader.getResourceAsStream("application.properties");
            }
            //创建一个Properties 对象
            loader=new Properties();
            //加载输入流
            loader.load(is);
            //生成公钥和私钥
            RSAUtils.genKeyPair();
            PUBLIC_KEY =  RSAUtils.keyMap.get(RSAUtils.PUBLIC_KEY);
            PRIVATE_KEY = RSAUtils.keyMap.get(RSAUtils.PRIVATE_KEY);
        }
        catch (IOException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
    }

**Comment by TomYule** [comment]
这个是少数情况 自行修改
