### ISSUE TITLE
请教个springboot连接oracle报账号密码错误的问题

### ISSUE THREAD

**Issue by EddyMVP** [TomYule/NutzSite#12]
你好，从这个链接http://www.nutz.cn/yvr/t/s2vuh1prdugn6q5u5pmj1l6fnl看到了你曾经的提问：
“oracle 使用入门到放弃errorCode 1017, state 72000 java.sql.SQLException: ORA-01017”
我遇到的情况跟你的一样，同样的账号密码，用pl/sql登录、用jdbc连接都没问题，但是一旦改用springboot连接oracle就报账号密码错误。数据库是oracle11g,springboot版本是1.5，服务器是centos7。
盼回复指教，方便的话加个微信：zhaoxin_most

**Comment by TomYule** [comment]
jdbc 配置问题 仔细核查

**Comment by EddyMVP** [comment]
配置核查很多遍了 我甚至把同样的程序同样的配置换了一台服务器部署就能连接上数据库 唯一的区别就是换的这台服务器没有安装数据库 而之前连接报账号密码错误的那台服务器是装有数据库的 十分奇怪
